### ISSUE TITLE
ValueError: invalid literal for float(): 0.0

### ISSUE THREAD

**Issue by jblaine** [datacratic/check_graphite#11]
<pre>
plugins:rcf-monitor> ./check_graphite -u 'https://rcf-metrics.our.org/render?target=linus.smtp.sent.*&from=-2minutes&rawData=true' -U nagios -P nagios
Traceback (most recent call last):
  File "./check_graphite", line 92, in <module>
    values = map(lambda x: 0.0 if x == 'None' else float(x), values)
  File "./check_graphite", line 92, in <lambda>
    values = map(lambda x: 0.0 if x == 'None' else float(x), values)
ValueError: invalid literal for float(): 0.0
</pre>

**Comment by jblaine** [comment]
The raw data from the above is:

<pre>
linus.smtp.sent.other,1354036320,1354036440,60|0.0,0.0
linus.smtp.sent.prog,1354036320,1354036440,60|0.0,0.0
linus.smtp.sent.relay,1354036320,1354036440,60|0.0,0.0
linus.smtp.sent.smtp,1354036320,1354036440,60|0.0,0.0
</pre>

**Comment by jblaine** [comment]
Additionally, showing it is not just a 0.0 issue (10 minutes back instead of 2):

<pre>
plugins:rcf-monitor> ./check_graphite -u 'https://rcf-metrics.our.org/render?target=linus.smtp.sent.*&from=-10minutes&rawData=true' -U nagios -P nagios
Traceback (most recent call last):
  File "./check_graphite", line 92, in <module>
    values = map(lambda x: 0.0 if x == 'None' else float(x), values)
  File "./check_graphite", line 92, in <lambda>
    values = map(lambda x: 0.0 if x == 'None' else float(x), values)
ValueError: invalid literal for float(): 0.0166666666667
linus.smtp.sent.prog
</pre>

**Comment by jblaine** [comment]
OHHHHH. I was specifying a wildcard in the metric specification.

**Comment by jblaine** [comment]
Addressed in https://github.com/datacratic/check_graphite/pull/12
